sudo: required
services:
  - docker

before_install:
  - docker build -t williampring/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true williampring/docker-react npm run test -- --coverage
