sudo: required
services:
  - docker

before_install:
  - docker build -t williampring/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true williampring/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-905226224725"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
