sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t williampring/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true williampring/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "React-Docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-905226224725"
  bucket_path: "React-Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
